version: '3'

x-common: &common-settings
  image: nginx
  restart: unless-stopped

services:
  webcam:
    <<: *common-settings
    container_name: webcam
    volumes:
      - /mnt/models/Webcam21:/usr/share/nginx/html:ro
    ports:
      - "8180:80"

  dogcam:
    <<: *common-settings
    container_name: dogcam
    volumes:
      - /mnt/models/Webcam22:/usr/share/nginx/html:ro
    ports:
      - "8280:80"

