#!/usr/bin/env bash
# Install (or refresh) the funes-vision systemd units and watchdog cron.
#
# Usage:
#   sudo bash systemd/install.sh
#
# Host identity and paths are read from /etc/webcam/webcam.env (see
# systemd/webcam.env.example). If that file does not exist, install.sh derives
# them from the invoking user and this checkout, then writes the file.
#
# This script is deliberately non-destructive: it never removes system paths
# (older versions `rm -rf`'d /usr/local/lib/ollama and friends). It installs
# over existing files and reloads systemd.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DIR="/etc/webcam"
ENV_FILE="$ENV_DIR/webcam.env"
SYSTEMD_DIR="/etc/systemd/system"

# The user that ran sudo, falling back to the current user. This is the
# default service account and the default cron owner.
INVOKING_USER="${SUDO_USER:-$(id -un)}"
if ! id "$INVOKING_USER" >/dev/null 2>&1; then
  INVOKING_USER="$(id -un)"
fi

# An existing /etc/webcam/webcam.env wins over every default below.
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

WEBCAM_USER="${WEBCAM_USER:-$INVOKING_USER}"
WEBCAM_GROUP="${WEBCAM_GROUP:-$(id -gn "$WEBCAM_USER" 2>/dev/null || echo "$WEBCAM_USER")}"
if [[ -z "${WEBCAM_HOME:-}" ]]; then
  WEBCAM_HOME="$(getent passwd "$WEBCAM_USER" 2>/dev/null | cut -d: -f6 || true)"
fi
WEBCAM_HOME="${WEBCAM_HOME:-/home/$WEBCAM_USER}"
WEBCAM_DIR="${WEBCAM_DIR:-$REPO_DIR}"
WEBCAM_CAMERAS="${WEBCAM_CAMERAS:-Webcam21 Webcam22}"
WEBCAM_MODELS_DIR="${WEBCAM_MODELS_DIR:-/mnt/models}"
WEBCAM_OLLAMA_BIN="${WEBCAM_OLLAMA_BIN:-$(command -v ollama 2>/dev/null || echo /usr/local/bin/ollama)}"
OLLAMA_MODELS="${OLLAMA_MODELS:-$WEBCAM_MODELS_DIR/ollama/models}"
OLLAMA_HOST="${OLLAMA_HOST:-127.0.0.1:11434}"
OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:-24h}"
# Browser origins allowed to WRITE to the API. Behind the reverse proxy the
# page and the API are the same origin and need no entry; this default only
# covers the documented LAN/dev path (the page opened straight on a camera
# container at :8180/:8280, where the SPA points cross-origin at :8190) as
# seen from this box. Operators reaching the gallery from another machine must
# add that machine's view of the address -- the box's LAN IP/hostname as typed
# into the address bar, e.g. http://192.168.1.50:8180 -- which is why the LAN
# forms are emitted as a commented hint below. `*` is NOT a valid value: it is
# refused, and it used to resolve to an allowlist of nothing at all, which 403'd
# every browser write while curl kept working (#51).
WEBCAM_CORS_ORIGIN="${WEBCAM_CORS_ORIGIN:-http://localhost:8180,http://127.0.0.1:8180,http://localhost:8280,http://127.0.0.1:8280}"
# Best-effort hint for LAN access; never auto-enabled, because the origin is
# whatever the *client* typed, not something this host can know.
WEBCAM_LAN_IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i < NF; i++) if ($i == "src") { print $(i + 1); exit }}')"

if ! id "$WEBCAM_USER" >/dev/null 2>&1; then
  echo "ERROR: WEBCAM_USER '$WEBCAM_USER' does not exist." >&2
  echo "Create it (e.g. useradd -m '$WEBCAM_USER') or set WEBCAM_USER in $ENV_FILE." >&2
  exit 1
fi

# Persist the resolved values so systemd's EnvironmentFile can read them.
install -d -m 755 "$ENV_DIR"
if [[ -f "$ENV_FILE" ]]; then
  echo "Using existing $ENV_FILE"
else
  cat > "$ENV_FILE" <<EOF
# Generated by systemd/install.sh on $(date -Is).
# Edit to change the host identity/paths, then re-run systemd/install.sh.
# See systemd/webcam.env.example for the full reference.
WEBCAM_USER=$WEBCAM_USER
WEBCAM_GROUP=$WEBCAM_GROUP
WEBCAM_HOME=$WEBCAM_HOME
WEBCAM_DIR=$WEBCAM_DIR
WEBCAM_CAMERAS="$WEBCAM_CAMERAS"
WEBCAM_MODELS_DIR=$WEBCAM_MODELS_DIR
WEBCAM_OLLAMA_BIN=$WEBCAM_OLLAMA_BIN
OLLAMA_MODELS=$OLLAMA_MODELS
OLLAMA_HOST=$OLLAMA_HOST
OLLAMA_KEEP_ALIVE=$OLLAMA_KEEP_ALIVE
WEBCAM_CORS_ORIGIN="$WEBCAM_CORS_ORIGIN"
EOF
  # LAN access is the one case this host cannot configure correctly on its
  # own: the browser's Origin is the address the *client* typed. Offer the
  # detected LAN IP as a commented line rather than guessing, since enabling
  # the wrong origin silently 403s and a right one silently widens who may
  # write (#51).
  if [[ -n "$WEBCAM_LAN_IP" ]]; then
    cat >> "$ENV_FILE" <<EOF
# LAN access: uncomment and adjust to the address your browser actually uses.
# WEBCAM_CORS_ORIGIN="$WEBCAM_CORS_ORIGIN,http://$WEBCAM_LAN_IP:8180,http://$WEBCAM_LAN_IP:8280"
EOF
  fi
  chmod 644 "$ENV_FILE"
  echo "Wrote $ENV_FILE"
fi

cat <<EOF
CORS origin allowlist: $WEBCAM_CORS_ORIGIN
  Same-origin writes (the reverse proxy: gallery and /api/ on one host) are
  accepted with no entry at all. Browsing straight to a camera container
  (:8180 front, :8280 back) is cross-origin and does need an entry; from
  another machine add http://<this-box-as-the-client-types-it>:8180. Verify
  with: journalctl -u webcam-api | grep 'CORS allowlist'
EOF

# systemd cannot expand environment variables in User=/Group=/HOME= or
# RequiresMountsFor=, so those values are rendered as __WEBCAM_*__ tokens.
# Runtime command paths still expand from the EnvironmentFile above.
render() {
  sed \
    -e "s|__WEBCAM_USER__|${WEBCAM_USER}|g" \
    -e "s|__WEBCAM_GROUP__|${WEBCAM_GROUP}|g" \
    -e "s|__WEBCAM_HOME__|${WEBCAM_HOME}|g" \
    -e "s|__WEBCAM_DIR__|${WEBCAM_DIR}|g" \
    -e "s|__WEBCAM_MODELS_DIR__|${WEBCAM_MODELS_DIR}|g" \
    "$1" > "$2"
}

for unit in webcam-pipeline@.service webcam-api.service ollama.service \
            webcam-compose.service webcam-healthcheck.service \
            webcam-healthcheck.timer; do
  render "$SCRIPT_DIR/$unit" "$SYSTEMD_DIR/$unit"
done
# webcam-healthcheck.service executes the script from WEBCAM_DIR so the
# watchdog always matches the deployed checkout instead of a stale copy.
systemctl daemon-reload

# Stop any ad-hoc watchers so systemd owns the processes.
pkill -f "create-inde[x].sh" || true
pkill -x inotifywait || true
sleep 1

# Stop any ad-hoc API/ollama instances so systemd owns them.
pkill -f "api_serve[r].py" || true
pkill -f "ollama-bin/bin/ollam[a]" || true

pipeline_units=()
for cam in $WEBCAM_CAMERAS; do
  pipeline_units+=("webcam-pipeline@${cam}")
done
systemctl enable --now "${pipeline_units[@]}" webcam-api ollama \
  webcam-compose webcam-healthcheck.timer

# The @reboot create-index cron entries are superseded by systemd; drop only
# those lines from the configured user's crontab. The system cron.d file below
# is canonical. Never touch any other user's crontab.
if command -v crontab >/dev/null 2>&1 && crontab -u "$WEBCAM_USER" -l >/dev/null 2>&1; then
  crontab -u "$WEBCAM_USER" -l 2>/dev/null \
    | grep -v 'create-index\.sh' \
    | grep -v 'webcam/tools/watchdog' \
    | crontab -u "$WEBCAM_USER" - || true
fi

cron_tmp="$(mktemp)"
render "$SCRIPT_DIR/webcam-watchdog.cron" "$cron_tmp"
install -m 644 "$cron_tmp" /etc/cron.d/webcam-watchdog
rm -f "$cron_tmp"
chmod +x "$WEBCAM_DIR/tools/watchdog.sh"

systemctl --no-pager status "${pipeline_units[@]}" 2>/dev/null | head -20 || true
echo "Done. Logs: journalctl -u ${pipeline_units[0]} -f"
echo "Watchdog: /etc/cron.d/webcam-watchdog (log: $WEBCAM_DIR/watchdog.log)"
