#!/usr/bin/env bash
# Install (or refresh) the funes-vision systemd units and watchdog cron.
#
# Usage:
#   sudo bash systemd/install.sh
#
# Host identity and paths are read from /etc/webcam/webcam.env (see
# systemd/webcam.env.example). If that file does not exist, install.sh derives
# them from the invoking user and this checkout, then writes the file.
#
# This script is deliberately non-destructive: it never removes system paths
# (older versions `rm -rf`'d /usr/local/lib/ollama and friends). It installs
# over existing files and reloads systemd.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_DIR="/etc/webcam"
ENV_FILE="$ENV_DIR/webcam.env"
SYSTEMD_DIR="/etc/systemd/system"

# The user that ran sudo, falling back to the current user. This is the
# default service account and the default cron owner.
INVOKING_USER="${SUDO_USER:-$(id -un)}"
if ! id "$INVOKING_USER" >/dev/null 2>&1; then
  INVOKING_USER="$(id -un)"
fi

# An existing /etc/webcam/webcam.env wins over every default below.
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

WEBCAM_USER="${WEBCAM_USER:-$INVOKING_USER}"
WEBCAM_GROUP="${WEBCAM_GROUP:-$(id -gn "$WEBCAM_USER" 2>/dev/null || echo "$WEBCAM_USER")}"
if [[ -z "${WEBCAM_HOME:-}" ]]; then
  WEBCAM_HOME="$(getent passwd "$WEBCAM_USER" 2>/dev/null | cut -d: -f6 || true)"
fi
WEBCAM_HOME="${WEBCAM_HOME:-/home/$WEBCAM_USER}"
WEBCAM_DIR="${WEBCAM_DIR:-$REPO_DIR}"
WEBCAM_CAMERAS="${WEBCAM_CAMERAS:-Webcam21 Webcam22}"
WEBCAM_MODELS_DIR="${WEBCAM_MODELS_DIR:-/mnt/models}"
WEBCAM_OLLAMA_BIN="${WEBCAM_OLLAMA_BIN:-$(command -v ollama 2>/dev/null || echo /usr/local/bin/ollama)}"
OLLAMA_MODELS="${OLLAMA_MODELS:-$WEBCAM_MODELS_DIR/ollama/models}"
OLLAMA_HOST="${OLLAMA_HOST:-127.0.0.1:11434}"
OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:-24h}"

if ! id "$WEBCAM_USER" >/dev/null 2>&1; then
  echo "ERROR: WEBCAM_USER '$WEBCAM_USER' does not exist." >&2
  echo "Create it (e.g. useradd -m '$WEBCAM_USER') or set WEBCAM_USER in $ENV_FILE." >&2
  exit 1
fi

# Persist the resolved values so systemd's EnvironmentFile can read them.
install -d -m 755 "$ENV_DIR"
if [[ -f "$ENV_FILE" ]]; then
  echo "Using existing $ENV_FILE"
else
  cat > "$ENV_FILE" <<EOF
# Generated by systemd/install.sh on $(date -Is).
# Edit to change the host identity/paths, then re-run systemd/install.sh.
# See systemd/webcam.env.example for the full reference.
WEBCAM_USER=$WEBCAM_USER
WEBCAM_GROUP=$WEBCAM_GROUP
WEBCAM_HOME=$WEBCAM_HOME
WEBCAM_DIR=$WEBCAM_DIR
WEBCAM_CAMERAS="$WEBCAM_CAMERAS"
WEBCAM_MODELS_DIR=$WEBCAM_MODELS_DIR
WEBCAM_OLLAMA_BIN=$WEBCAM_OLLAMA_BIN
OLLAMA_MODELS=$OLLAMA_MODELS
OLLAMA_HOST=$OLLAMA_HOST
OLLAMA_KEEP_ALIVE=$OLLAMA_KEEP_ALIVE
EOF
  chmod 644 "$ENV_FILE"
  echo "Wrote $ENV_FILE"
fi

# systemd cannot expand environment variables in User=/Group=/HOME=, so those
# three are shipped as __WEBCAM_*__ tokens and substituted here. Every other
# path is expanded at runtime from the EnvironmentFile above.
render() {
  sed \
    -e "s|__WEBCAM_USER__|${WEBCAM_USER}|g" \
    -e "s|__WEBCAM_GROUP__|${WEBCAM_GROUP}|g" \
    -e "s|__WEBCAM_HOME__|${WEBCAM_HOME}|g" \
    -e "s|__WEBCAM_DIR__|${WEBCAM_DIR}|g" \
    "$1" > "$2"
}

for unit in webcam-pipeline@.service webcam-api.service ollama.service webcam-compose.service; do
  render "$SCRIPT_DIR/$unit" "$SYSTEMD_DIR/$unit"
done
systemctl daemon-reload

# Stop any ad-hoc watchers so systemd owns the processes.
pkill -f "create-inde[x].sh" || true
pkill -x inotifywait || true
sleep 1

# Stop any ad-hoc API/ollama instances so systemd owns them.
pkill -f "api_serve[r].py" || true
pkill -f "ollama-bin/bin/ollam[a]" || true

pipeline_units=()
for cam in $WEBCAM_CAMERAS; do
  pipeline_units+=("webcam-pipeline@${cam}")
done
systemctl enable --now "${pipeline_units[@]}" webcam-api ollama

# The @reboot create-index cron entries are superseded by systemd; drop only
# those lines from the configured user's crontab. The system cron.d file below
# is canonical. Never touch any other user's crontab.
if command -v crontab >/dev/null 2>&1 && crontab -u "$WEBCAM_USER" -l >/dev/null 2>&1; then
  crontab -u "$WEBCAM_USER" -l 2>/dev/null \
    | grep -v 'create-index\.sh' \
    | grep -v 'webcam/tools/watchdog' \
    | crontab -u "$WEBCAM_USER" - || true
fi

cron_tmp="$(mktemp)"
render "$SCRIPT_DIR/webcam-watchdog.cron" "$cron_tmp"
install -m 644 "$cron_tmp" /etc/cron.d/webcam-watchdog
rm -f "$cron_tmp"
chmod +x "$WEBCAM_DIR/tools/watchdog.sh"

systemctl --no-pager status "${pipeline_units[@]}" 2>/dev/null | head -20 || true
echo "Done. Logs: journalctl -u ${pipeline_units[0]} -f"
echo "Watchdog: /etc/cron.d/webcam-watchdog (log: $WEBCAM_DIR/watchdog.log)"
